---
title: "R Notebook"
output: 
  github_document:
    toc: true
    toc_depth: 2
---

```{r}
library (phyloseq)
library(ggplot2)
library (dada2)
```

#création variable
```{r}
path <- "~/CC2_ECOG/sequences_reunies" # CHANGE ME to the directory containing the fastq files after unzipping.
list.files(path)
```
## filtration et retirage des sequences basse qualité
```{r}
# Sort ensures forward/reverse reads are in same order
fnFs <- sort(list.files(path, pattern="_R1.fastq"))
fnRs <- sort(list.files(path, pattern="_R2.fastq"))
# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names <- sapply(strsplit(basename(fnFs), "R"), `[`,1)
# Specify the full path to the fnFs and fnRs
fnFs <- file.path(path, fnFs)
fnRs <- file.path(path, fnRs)
print(fnRs)
```

```{r}
fnRs[1:11]
```

```{r}
plotQualityProfile(fnFs[1:3])
```



```{r}
plotQualityProfile(fnRs[1:2])
```

```{r}
# Place filtered files in filtered/ subdirectory
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
sample.names
print(filtFs)
```

```{r}
out<-filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(210,150),trimLeft=c(21,0),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE) # On Windows set multithread=FALSE
head(out)
```

